DEBUG = 1

COUNTRIES = [
    'afghanistan'
    , 'albania'
    , 'algeria'
    , 'andorra'
    , 'angola'
    , 'antigua-and-barbados'
    , 'argentina'
    , 'armenia'
    , 'australia'
    , 'austria'
    , 'azerbaijan'
    , 'bahamas'
    , 'bahrain'
    , 'bangladesh'
    , 'barbados'
    , 'belarus'
    , 'belgium'
    , 'belize'
    , 'benin'
    , 'bhutan'
    , 'bolivia'
    , 'bosnia-herzegovina'
    , 'botswana'
    , 'brazil'
    , 'brunei'
    , 'bulgaria'
    , 'burkina'
    , 'burundi'
    , 'cambodia'
    , 'cameroon'
    , 'canada'
    , 'cape-verde'
    , 'central-african-rep'
    , 'chad'
    , 'chile'
    , 'china'
    , 'colombia'
    , 'comoros'
    , 'congo'
    , 'congo'
    , 'costa-rica'
    , 'croatia'
    , 'cuba'
    , 'cyprus'
    , 'czech-republic'
    , 'denmark'
    , 'djibouti'
    , 'dominica'
    , 'dominican-republic'
    , 'east-timor'
    , 'ecuador'
    , 'egypt'
    , 'el-salvador'
    , 'equatorial-guinea'
    , 'eritrea'
    , 'estonia'
    , 'ethiopia'
    , 'fiji'
    , 'finland'
    , 'france'
    , 'gabon'
    , 'gambia'
    , 'georgia'
    , 'germany'
    , 'ghana'
    , 'greece'
    , 'grenada'
    , 'guatemala'
    , 'guinea'
    , 'guinea-bissau'
    , 'guyana'
    , 'haiti'
    , 'honduras'
    , 'hungary'
    , 'iceland'
    , 'india'
    , 'indonesia'
    , 'iran'
    , 'iraq'
    , 'ireland'
    , 'israel'
    , 'italy'
    , 'ivory-coast'
    , 'jamaica'
    , 'japan'
    , 'jordan'
    , 'kazakhstan'
    , 'kenya'
    , 'kiribati'
    , 'korea-north'
    , 'korea-south'
    , 'kosovo'
    , 'kuwait'
    , 'kyrgyzstan'
    , 'laos'
    , 'latvia'
    , 'lebanon'
    , 'lesotho'
    , 'liberia'
    , 'libya'
    , 'liechtenstein'
    , 'lithuania'
    , 'luxembourg'
    , 'macedonia'
    , 'madagascar'
    , 'malawi'
    , 'malaysia'
    , 'maldives'
    , 'mali'
    , 'malta'
    , 'marshall-islands'
    , 'mauritania'
    , 'mauritius'
    , 'mexico'
    , 'micronesia'
    , 'moldova'
    , 'monaco'
    , 'mongolia'
    , 'montenegro'
    , 'morocco'
    , 'mozambique'
    , 'myanmar'
    , 'namibia'
    , 'nauru'
    , 'nepal'
    , 'netherlands'
    , 'new-zealand'
    , 'nicaragua'
    , 'niger'
    , 'nigeria'
    , 'norway'
    , 'oman'
    , 'pakistan'
    , 'palau'
    , 'panama'
    , 'papua-new-guinea'
    , 'paraguay'
    , 'peru'
    , 'philippines'
    , 'poland'
    , 'portugal'
    , 'qatar'
    , 'romania'
    , 'russian-federation'
    , 'rwanda'
    , 'st-kitts-nevis'
    , 'st-lucia'
    , 'saint-vincent-the-grenadines'
    , 'samoa'
    , 'san-marino'
    , 'sao-tome-principe'
    , 'saudi-arabia'
    , 'senegal'
    , 'serbia'
    , 'seychelles'
    , 'sierra-leone'
    , 'singapore'
    , 'slovakia'
    , 'slovenia'
    , 'solomon-islands'
    , 'somalia'
    , 'south-africa'
    , 'south-sudan'
    , 'spain'
    , 'sri-lanka'
    , 'sudan'
    , 'suriname'
    , 'swaziland'
    , 'sweden'
    , 'switzerland'
    , 'syria'
    , 'taiwan'
    , 'tajikistan'
    , 'tanzania'
    , 'thailand'
    , 'togo'
    , 'tonga'
    , 'trinidad-tobago'
    , 'tunisia'
    , 'turkey'
    , 'turkmenistan'
    , 'tuvalu'
    , 'uganda'
    , 'ukraine'
    , 'united-arab-emirates'
    , 'united-kingdom'
    , 'united-states'
    , 'uruguay'
    , 'uzbekistan'
    , 'vanuatu'
    , 'vatican-city'
    , 'venezuela'
    , 'vietnam'
    , 'yemen'
    , 'zambia'
    , 'zimbabwe'
]

YEARS = [
    "2021"
    , "2020"
    , "2019"
    , "2018"
    , "2017"
    , "2016"
#    , "2015"
#    , "2014"
#    , "2013"
#    , "2012"
]

HR_CONFIG = {

    "baseURL": "https://www.state.gov/reports/{year}-country-reports-on-human-rights-practices/"
    , "q": [
        "year"
    ]

}

UN_CONFIG = {
    
    "baseURL": "https://digitallibrary.un.org/search?cc=Voting+Data&ln=en&c=Voting+Data&rg={nrecords}&jrec={start}&fct__3={year}&fct__9=Vote"
    , "q": [
        "start"
        , "nrecords"
        , "year"
    ]

}
